[build]
dockerfilePath = "apps/wchan-vault-indexer/Dockerfile"

[deploy]
startCommand = "sh -c 'pnpm ponder start --port 42072 --schema $RAILWAY_DEPLOYMENT_ID'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
