[build]
dockerfilePath = "apps/indexer/Dockerfile"

[deploy]
startCommand = "pnpm ponder start --schema $RAILWAY_DEPLOYMENT_ID"
healthcheckPath = "/ready"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
